# general
run_name: 'test' #'augmented_version'
seed: 0 # run seed

# channel
channel_type: 'MIMO' # Channel type values: ['SISO','MIMO']. For this paper, we only used ISI AWGN/SED.
fading_in_channel: False # If the channel is fading/non-fading. values: [True, False]

# augmentations
# ['no_aug','full_knowledge_augmenter','partial_knowledge_augmenter','geometric_augmenter','flipping_augmenter','border_smote_augmenter']
aug_type: ['border_smote_augmenter']
online_repeats_n: 500 # number of desired augmented words out of online_total_words. values: 0<=online_repeats_n<=online_total_words

# validation hyperparameters
val_block_length: 5100 # coherence block time, total size of pilot + data. values: int.
pilot_size: 100 # pilot symbols
val_frames: 10 # number of validation frames. values: int.
val_snr: 12 # start SNR value. values: float.
eval_mode: 'by_word' # Type of evaluation per block - 'by_word'.

# online training hyperparameters
is_online_training: True # Whether to run the online training (as in ViterbiNet). values: [True, False].
train_minibatch_size: 32 # the size of a given minibatch. values: int.
lr: 0.001 # learning rate. values: float.
loss_type: 'CrossEntropy' # Loss type. values: 'BCE','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.
from_scratch_flag: True # whether to initialize the detector at each new channel instance (True) or continue from previous weights (False)