# general
run_name: 'test' #'augmented_version'
seed: 0 # run seed

# channel
channel_type: 'SISO' # Channel type values: ['SISO','MIMO'].
channel_model: 'Synthetic' # Physical channel models: ['Cost2100','Synthetic']
detector_type: 'model' # 'model' or 'black_box'
linear: True # channel linearity. Boolean value.
fading_in_channel: True # If the channel is fading/non-fading. values: [True, False]
modulation_type: 'BPSK' # ['BPSK','QPSK']

# sampler
sampler_type: 'geometric_sampler' # 'no_sampler', 'geometric_sampler', 'full_knowledge_sampler'
aug_type: [  ] # ['translation_augmenter','rotation_augmenter']
online_repeats_n: 1000 # number of desired augmented words out of online_total_words. values: online_total_words<=online_repeats_n

# validation hyperparameters
val_block_length: 10200 # coherence block time, total size of pilot + data. values: int.
pilot_size: 200 # pilot symbols
blocks_num: 20 # number of validation frames. values: int.
val_snr: 12 # start SNR value. values: float.
eval_mode: 'by_word' # Type of evaluation per block - 'by_word'.

# online training hyperparameters
is_online_training: True # Whether to run the online training (as in ViterbiNet). values: [True, False].
loss_type: 'CrossEntropy' # Loss type. values: 'BCE','CrossEntropy','MSE'.
optimizer_type: 'Adam' # Optimizer type. values: 'Adam','RMSprop','SGD'.
from_scratch: False